name: Deploy to EC2 using ssh deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy files via SSH
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          SOURCE: "./"
          TARGET: "/var/www/itdefined.com/"
          ARGS: "-rlptDzv --chmod=755 --chown=${{ secrets.SSH_USERNAME }}:www-data --delete"
          PRE_SCRIPTS: |
            echo "Preparing directory..."
            sudo mkdir -p /var/www/itdefined.com
            sudo chown -R ${{ secrets.SSH_USERNAME }}:www-data /var/www/itdefined.com
          POST_SCRIPTS: |
            echo "Finalizing permissions..."
            sudo chown -R www-data:www-data /var/www/itdefined.com
            sudo find /var/www/itdefined.com -type d -exec chmod 755 {} \;
            sudo find /var/www/itdefined.com -type f -exec chmod 644 {} \;
            sudo systemctl restart nginx